version: 0.0
os: linux
files:
  - source: ./willy-0.16.1-jar-with-dependencies.jar
    destination: /bin/willy
  - source: ./after-install.sh
    destination: /bin/willy
  - source: ./application-start.sh
    destination: /bin/willy
  - source: ./application-stop.sh
    destination: /bin/willy
hooks:
  BeforeInstall:
    - location: /bin/willy/before-install.sh
  AfterInstall:
    - location: /bin/willy/after-install.sh
  ApplicationStart:
    - location: /bin/willy/application-start.sh
  ApplicationStop:
    - location: /bin/willy/application-stop.sh