version: 0.0
os: linux
files:
  - source: ./willy-0.16.1-jar-with-dependencies.jar
    destination: ~/
  - source: ./after-install
    destination: ~/
  - source: ./application-start
    destination: ~/
  - source: ./application-stop
    destination: ~/
hooks:
  AfterInstall:
    - location: ./after-install
  ApplicationStart:
    - location: ./application-start
  ApplicationStop:
    - location: ./application-stop