version: 0.0
os: linux
files:
  - source: ./willy-0.17.0-jar-with-dependencies.jar
    destination: /
  - source: ./after-install.sh
    destination: /
  - source: ./application-start.sh
    destination: /
  - source: ./application-stop.sh
    destination: /
hooks:
  BeforeInstall:
    - location: /before-install.sh
  AfterInstall:
    - location: /after-install.sh
  ApplicationStart:
    - location: /application-start.sh
  ApplicationStop:
    - location: /application-stop.sh