# ---------------------------------------------------------- #
#                                                            #
#                    Willy Bot Config File                   #
#                                                            #
#     For help check https://github.com/laravieira/Willy     #
#                                                            #
# ---------------------------------------------------------- #

environment: development
context-life-time: 5m

discord:
    enable: false
    client-id:
    token:
    keep-willy-nick: true
    keep-master-nick:
    public-chat:
        enable: true
        willy-names:
            - Willy
            - willy
        ignore-start-with:
            - "!"
            - "?"
            - "@"
            - "/"
            - "#"
        auto-delete:
            willy-messages: false
            delete-after-wait: 10m
    admin:
        guild:
        command:
        log:

openai:
    enable: false
    token:
    dall-e: false

whatsapp:
    enable: false
    phone-number:
    group: # Not implemented yet
        enable: false
        willy-names:
            - Willy
            - willy
        ignore-start-with:
            - "!"
            - "?"
            - "@"
            - "/"
            - "#"
        auto-delete:
            willy-messages: false
            delete-after-wait: 10m

telegram:
    enable: false
    token:
    group: # Not implemented yet
        enable: false
        willy-names:
            - Willy
            - willy
        ignore-start-with:
            - "!"
            - "?"
            - "@"
            - "/"
            - "#"
        auto-delete:
            willy-messages: false
            delete-after-wait: 10m

bitly:
    enable: false
    token:

http-api:
    enable: true
    port: 7001
