FROM maven:3-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . .
RUN mvn clean install package


FROM openjdk:21-jdk-slim
WORKDIR /app

ENV BUILD_NAME willy-0.17.0-jar-with-dependencies.jar
ENV ENVIRONMENT production
ENV WILLY_CONTEXT_LIFETIME 5m
ENV MEMORY 1G

ENV WILLY_DISCORD_ENABLE false
ENV WILLY_DISCORD_CLIENT_ID 0
ENV WILLY_DISCORD_TOKEN ''
ENV WILLY_DISCORD_KEEP_NICK_WILLY true
ENV WILLY_DISCORD_KEEP_NICK_MASTER 0
ENV WILLY_DISCORD_ADMIN_GUILD 0
ENV WILLY_DISCORD_ADMIN_COMMAND 0
ENV WILLY_DISCORD_ADMIN_LOG 0
ENV WILLY_DISCORD_PUBLIC_CHAT_ENABLE false
ENV WILLY_DISCORD_PUBLIC_CHAT_WILLY_NAMES 'Willy|willy'
ENV WILLY_DISCORD_PUBLIC_CHAT_IGNORE_START_WITH '!|?|@|/|#'
ENV WILLY_DISCORD_PUBLIC_CHAT_AUTO_DELETE_WILLY_MESSAGES false
ENV WILLY_DISCORD_PUBLIC_CHAT_AUTO_DELETE_DELETE_AFTER_WAIT 10m

ENV WILLY_OPENAI_ENABLE false
ENV WILLY_OPENAI_TOKEN ''
ENV WILLY_OPENAI_DALL_E false

ENV WILLY_WHATSAPP_ENABLE false
ENV WILLY_WHATSAPP_PHONE_NUMBER 0
ENV WILLY_WHATSAPP_GROUP_ENABLE false
ENV WILLY_WHATSAPP_GROUP_WILLY_NAMES 'Willy|willy'
ENV WILLY_WHATSAPP_GROUP_IGNORE_START_WITH '!|?|@|/|#'
ENV WILLY_WHATSAPP_GROUP_AUTO_DELETE_WILLY_MESSAGES false
ENV WILLY_WHATSAPP_GROUP_AUTO_DELETE_DELETE_AFTER_WAIT 10m

ENV WILLY_TELEGRAM_ENABLE false
ENV WILLY_TELEGRAM_TOKEN ''
ENV WILLY_TELEGRAM_GROUP_ENABLE false
ENV WILLY_TELEGRAM_GROUP_WILLY_NAMES 'Willy|willy'
ENV WILLY_TELEGRAM_GROUP_IGNORE_START_WITH '!|?|@|/|#'
ENV WILLY_TELEGRAM_GROUP_AUTO_DELETE_WILLY_MESSAGES false
ENV WILLY_TELEGRAM_GROUP_AUTO_DELETE_DELETE_AFTER_WAIT 10m

ENV WILLY_BITLY_ENABLE false
ENV WILLY_BITLY_TOKEN ''

ENV WILLY_HTTP_API_ENABLE true
ENV WILLY_HTTP_API_PORT 7001

COPY --from=build /app/target/$BUILD_NAME /app
EXPOSE $WILLY_HTTP_API_PORT

CMD java -Xmx$MEMORY --enable-preview -jar $BUILD_NAME
