package me.laravieira.willy;

import lombok.Getter;
import lombok.Setter;
import me.laravieira.willy.internal.Config;
import me.laravieira.willy.utils.PassedInterval;
import org.jetbrains.annotations.NotNull;

import java.util.*;

public class Context {
    private static final Map<UUID, Context> contexts = new HashMap<>();

    /** Get of create an instance of Context with id, should not be used by brain since it never starts a chat
     * @param id The unique identifier of the context, should be generated by the chat
     * @param sender The channel to sends responses to
     * @param app The app that started the chat
     * @param user The user who started the chat
     */
    @NotNull
    public static Context of(@NotNull UUID id, @NotNull WillyChannel sender, @NotNull String app, @NotNull String user) {
        contexts.putIfAbsent(id, new Context(id, sender, app, user));
        return contexts.get(id);
    }

    /** Get an instance of Context with id or null, should be used only by brain since it never starts a chat */
    public static Context of(@NotNull UUID id) {
        return contexts.get(id);
    }

    /** Check if a Context with id exists */
    public static boolean has(@NotNull UUID id) {
        return contexts.containsKey(id);
    }

    /** Clean up context and its messages after expiration time */
    public static void refresh() {
        try {
            List<UUID> delete = new ArrayList<>();
            contexts.forEach((id, context) -> {
                if (context.getExpire().hasPassedInterval())
                    delete.add(id);

                List<WillyMessage> messages = new ArrayList<>();
                context.messages.forEach(message -> {
                    if (message.getExpire() != null && message.getExpire().hasPassedInterval())
                        messages.add(message);
                });
                messages.forEach(message -> {
                    context.messages.removeIf(m -> m.getId().equals(message.getId()));
                    message.destroy();
                });
            });
            delete.forEach(Context::destroy);
        } catch (RuntimeException ignored) {}
    }

    /** Get the number of contexts */
    public static int size() {
        return contexts.size();
    }

    /** Get all contexts available */
    public static Map<UUID, Context> all() {
        return contexts;
    }

    /** Destroy a context and everything with it */
    public static void destroy(@NotNull UUID id) {
        if(has(id)) {
            Context context = of(id);
            for(WillyMessage message : context.messages)
                message.destroy();
            context.messages.clear();
            contexts.remove(id);
        }
    }

    @Getter
    private final PassedInterval expire = new PassedInterval(Config.getLong("context_lifetime"));
    @Getter
    private final UUID id;
    @Getter
    private final WillyChannel channel;
    @Getter
    private final LinkedList<WillyMessage> messages = new LinkedList<>();
    @Getter
    @Setter
    private String user;
    @Getter
    @Setter
    private String language = "default";
    @Getter
    private String app;

    private Context(@NotNull UUID id, @NotNull WillyChannel channel, @NotNull String app, @NotNull String user) {
        this.id = id;
        this.channel = channel;
        this.channel.setContext(this);
        this.user = user;
        this.expire.start();
        this.app = app;
    }

    /** Append message without sending to user or AI */
    public void append(@NotNull WillyMessage message) {
        message.context = this;
        messages.add(message);
    }

    /** Send a response to the user */
    public void respond(@NotNull WillyMessage message) {
        message.context = this;
        if(message.getFrom() == null)
            message.setFrom(Willy.getBrain().getName());
        if(message.getTo() == null)
            message.setTo(user);
        messages.add(message);

        // Detach to avoid timeout
        Thread thread = new Thread(channel::sendLast);
        thread.setDaemon(true);
        thread.start();
    }

    /** Send the user message to IA */
    public void process(@NotNull WillyMessage message) {
        message.context = this;
        if(message.getFrom() == null)
            message.setFrom(user);
        if(message.getTo() == null)
            message.setTo(Willy.getBrain().getName());
        messages.add(message);

        // Detach to avoid timeout
        Thread thread = new Thread(() -> Willy.getBrain().getChannel(this).sendLast());
        thread.setDaemon(true);
        thread.start();
    }
}
